/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.88
 * Generated at: 2024-05-19 05:03:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class driverlogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<!-- Design by foolishdeveloper.com -->\r\n");
      out.write("    <title></title>\r\n");
      out.write(" \r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <!--Stylesheet-->\r\n");
      out.write("    <style media=\"screen\">\r\n");
      out.write("      *,\r\n");
      out.write("*:before,\r\n");
      out.write("*:after{\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("body{\r\n");
      out.write("    background-color: #080710;\r\n");
      out.write("}\r\n");
      out.write(".background{\r\n");
      out.write("    width: 430px;\r\n");
      out.write("    height: 520px;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    transform: translate(-50%,-50%);\r\n");
      out.write("    left: 50%;\r\n");
      out.write("    top: 50%;\r\n");
      out.write("}\r\n");
      out.write(".background .shape{\r\n");
      out.write("    height: 200px;\r\n");
      out.write("    width: 200px;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("}\r\n");
      out.write(".shape:first-child{\r\n");
      out.write("    background: linear-gradient(\r\n");
      out.write("        #1845ad,\r\n");
      out.write("        #23a2f6\r\n");
      out.write("    );\r\n");
      out.write("    left: -80px;\r\n");
      out.write("    top: -80px;\r\n");
      out.write("}\r\n");
      out.write(".shape:last-child{\r\n");
      out.write("    background: linear-gradient(\r\n");
      out.write("        to right,\r\n");
      out.write("        #ff512f,\r\n");
      out.write("        #f09819\r\n");
      out.write("    );\r\n");
      out.write("    right: -30px;\r\n");
      out.write("    bottom: -80px;\r\n");
      out.write("}\r\n");
      out.write("form{\r\n");
      out.write("    height: 520px;\r\n");
      out.write("    width: 400px;\r\n");
      out.write("    background-color: rgba(255,255,255,0.13);\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    transform: translate(-50%,-50%);\r\n");
      out.write("    top: 50%;\r\n");
      out.write("    left: 50%;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    backdrop-filter: blur(10px);\r\n");
      out.write("    border: 2px solid rgba(255,255,255,0.1);\r\n");
      out.write("    box-shadow: 0 0 40px rgba(8,7,16,0.6);\r\n");
      out.write("    padding: 50px 35px;\r\n");
      out.write("}\r\n");
      out.write("form *{\r\n");
      out.write("    font-family: 'Poppins',sans-serif;\r\n");
      out.write("    color: #ffffff;\r\n");
      out.write("    letter-spacing: 0.5px;\r\n");
      out.write("    outline: none;\r\n");
      out.write("    border: none;\r\n");
      out.write("}\r\n");
      out.write("form h3{\r\n");
      out.write("    font-size: 32px;\r\n");
      out.write("    font-weight: 500;\r\n");
      out.write("    line-height: 42px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("label{\r\n");
      out.write("    display: block;\r\n");
      out.write("    margin-top: 30px;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    font-weight: 500;\r\n");
      out.write("}\r\n");
      out.write("input{\r\n");
      out.write("    display: block;\r\n");
      out.write("    height: 50px;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    background-color: rgba(255,255,255,0.07);\r\n");
      out.write("    border-radius: 3px;\r\n");
      out.write("    padding: 0 10px;\r\n");
      out.write("    margin-top: 8px;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    font-weight: 300;\r\n");
      out.write("}\r\n");
      out.write("::placeholder{\r\n");
      out.write("    color: #e5e5e5;\r\n");
      out.write("}\r\n");
      out.write(".login-btn{\r\n");
      out.write("    margin-top: 50px;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    background-color: #ffffff;\r\n");
      out.write("    color: #080710;\r\n");
      out.write("    padding: 15px 0;\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write(".social{\r\n");
      out.write("  margin-top: 30px;\r\n");
      out.write("  display: flex;\r\n");
      out.write("}\r\n");
      out.write(".social div{\r\n");
      out.write("  background: red;\r\n");
      out.write("  width: 150px;\r\n");
      out.write("  border-radius: 3px;\r\n");
      out.write("  padding: 5px 10px 10px 5px;\r\n");
      out.write("  background-color: rgba(255,255,255,0.27);\r\n");
      out.write("  color: #eaf0fb;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("}\r\n");
      out.write(".social div:hover{\r\n");
      out.write("  background-color: rgba(255,255,255,0.47);\r\n");
      out.write("}\r\n");
      out.write(".social .fb{\r\n");
      out.write("  margin-left: 25px;\r\n");
      out.write("}\r\n");
      out.write(".social i{\r\n");
      out.write("  margin-right: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button{\r\n");
      out.write("    height: 50px;\r\n");
      out.write("    width: 200px;\r\n");
      out.write("    background-color: white;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    transform: translate(-50%,-50%);\r\n");
      out.write("    top: 78%;\r\n");
      out.write("    left: 50%;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    backdrop-filter: blur(10px);\r\n");
      out.write("    border: 2px solid rgba(255,255,255,0.1);\r\n");
      out.write("    box-shadow: 0 0 40px rgba(8,7,16,0.6);\r\n");
      out.write("    padding: px px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a{\r\n");
      out.write("    color: #ff6b81;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("a:hover{\r\n");
      out.write("    color: #ff4757;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <div class=\"background\">\r\n");
      out.write("        <div class=\"shape\"></div>\r\n");
      out.write("        <div class=\"shape\"></div>\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("    <form action=\"logdri\" method=\"post\">\r\n");
      out.write("        <h3>Driver Login Here</h3>\r\n");
      out.write("\r\n");
      out.write("        <label for=\"username\">email</label>\r\n");
      out.write("        <input type=\"text\" placeholder=\"Email\" id=\"Email\" name=\"demail\">\r\n");
      out.write("\r\n");
      out.write("        <label for=\"PhoneNumber\">Phone no</label>\r\n");
      out.write("        <input type=\"number\" placeholder=\"Phone\" id=\"Phone\" name=\"dphone\">\r\n");
      out.write("\r\n");
      out.write("        <input type=\"submit\" name=\"submit\" value=\"Login\" class=\"login-btn\">\r\n");
      out.write("        <div class=\"social\">\r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("    \r\n");
      out.write("    <button ><a href=\"driverinsert.jsp\">Create Driver Account</a></button>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
